In [2]:
import numpy as np
import sys

# The Basics

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
a.ndim

1

In [6]:
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('float64')

In [10]:
a.itemsize

4

In [11]:
a.size

3

In [12]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
a[1,5]

13

In [14]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
a[:,2]

array([ 3, 10])

In [16]:
a[0,1:6:2]

array([2, 4, 6])

In [17]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [19]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [20]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [21]:
np.random.rand(4,2)

array([[0.17160667, 0.2387877 ],
       [0.32096024, 0.88892537],
       [0.76090189, 0.17959127],
       [0.56749807, 0.63330195]])

In [22]:
np.random.random_sample(a.shape)

array([[0.08462235, 0.63244819, 0.30130781, 0.59818918, 0.85152437,
        0.97850798, 0.09210149],
       [0.4062639 , 0.31906198, 0.79271344, 0.14193655, 0.2257396 ,
        0.96649547, 0.25413995]])

In [23]:
np.random.rand(*a.shape)

array([[0.46540627, 0.12693948, 0.88454773, 0.65941136, 0.64665467,
        0.57554424, 0.09569256],
       [0.53494598, 0.30385875, 0.26300282, 0.71784802, 0.76979743,
        0.1638577 , 0.25935893]])

In [24]:
np.random.randint(7,size=(3,3))

array([[1, 6, 1],
       [5, 6, 3],
       [6, 0, 4]])

In [25]:
np.random.randint(4,7,size=(3,3))

array([[5, 4, 5],
       [6, 5, 6],
       [6, 6, 4]])

In [26]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [28]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


## Copying Arrays

In [29]:
a=np.array([1,2,3])
b=a.copy()

In [30]:
b

array([1, 2, 3])

### Mathematics

In [31]:
a+2

array([3, 4, 5])

In [32]:
a-2

array([-1,  0,  1])

In [33]:
a*2

array([2, 4, 6])

In [34]:
1/a

array([1.        , 0.5       , 0.33333333])

In [35]:
a**2

array([1, 4, 9], dtype=int32)

In [36]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [37]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

## Linear Algebra

In [38]:
a=np.ones((2,3))

In [39]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
b=np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [41]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [43]:
c=np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [44]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.min(stats)

1

In [46]:
np.min(stats,axis=0)

array([1, 2, 3])

In [47]:
np.max(stats,axis=1)

array([3, 6])

In [48]:
np.sum(stats)

21

### Reorganizing Arrays

In [49]:
before=np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
before.shape

(2, 4)

In [51]:
after=before.reshape((4,2))

In [52]:
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [69]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
y=np.vstack([v1,v2,v2,v2])
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [56]:
h1=np.ones((2,4))
h2=np.zeros((2,2))
x=np.hstack([h1,h2])

In [57]:
x

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [58]:
x=x.astype('int32')

In [59]:
x

array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0]])

### Miscellaneous

In [60]:
filedata=np.genfromtxt('np_data.txt',delimiter=',')

In [62]:
filedata=filedata.astype('int32')

In [63]:
filedata

array([[ 1,  0,  1,  0,  3,  1,  0,  1,  1,  2,  0,  0],
       [ 0,  1,  1,  4,  2,  0,  1,  1, 18,  2,  0,  0]])

#### Boolean Masking and Advanced Indexing

In [65]:
filedata=filedata[filedata>1]

In [66]:
filedata

array([ 3,  2,  4,  2, 18,  2])

In [67]:
filedata[[1,2,5]]

array([2, 4, 2])

In [70]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [75]:
o=np.any(y>6,axis=1)
o

array([False,  True,  True,  True])

In [76]:
y[o]

array([[5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [77]:
o=np.any(y>6)
o

True

In [78]:
((filedata>3)&(filedata<5))

array([False, False,  True, False, False, False])

In [80]:
np.savetxt('saved.txt',y,delimiter='\t',fmt='%d')

In [83]:
with open('saved.txt', 'r') as f:
    for lines in f.readlines():
        print(lines)

1	2	3	4

5	6	7	8

5	6	7	8

5	6	7	8

